
sudo: required

language: java

services:
- docker

after_success:
- docker network create --driver bridge datalink
- docker pull mongo
- docker run -d --name mongo-dbserver --network datalink mongo
- docker build -t group14 .
- docker run group14